# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ubuntu-32" do |u32|
    u32.vm.box = "ubuntu/trusty32"

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    u32.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty32/versions/20150430.0.0/providers/virtualbox.box"
  end

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share the Nightingale source
  config.vm.synced_folder "../nightingale-hacking", "/nightingale-hacking"

  config.vm.provision :shell, path: "setup_box.sh"

  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  # end
end
